# Generated by Django 4.2.7 on 2026-01-29 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('rol', models.CharField(choices=[('jefe', 'Jefe'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico')], default='tecnico', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='última actividad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registros de actividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='app_usuario_email_00f306_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='app_usuario_rol_db79e1_idx'),
        ),
    ]
