# Generated by Django 4.2.7 on 2026-01-29 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancinIndividual',
            fields=[
                ('serial', models.CharField(help_text='Ej: BAL-001', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Serial')),
                ('estado', models.CharField(choices=[('almacen', 'En almacén'), ('servicio', 'En servicio'), ('mantenimiento', 'En mantenimiento'), ('baja', 'Dado de baja')], default='almacen', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True, verbose_name='Último movimiento')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('ubicacion_actual', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Balancín Individual',
                'verbose_name_plural': 'Balancines Individuales',
                'ordering': ['tipo', 'serial'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_restante', models.PositiveIntegerField(verbose_name='Stock restante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Historial de Repuesto',
                'verbose_name_plural': 'Historial de Repuestos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoAdicional',
            fields=[
                ('item', models.CharField(help_text='Ej: ADIC-001', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True, verbose_name='Último movimiento')),
                ('fecha_ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Última salida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Repuesto Adicional',
                'verbose_name_plural': 'Repuestos Adicionales',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoBalancin',
            fields=[
                ('item', models.CharField(help_text='Ej: REP-BAL-001', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True, verbose_name='Último movimiento')),
                ('fecha_ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Última salida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Repuesto para Balancín',
                'verbose_name_plural': 'Repuestos para Balancines',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='TipoBalancin',
            fields=[
                ('codigo', models.CharField(help_text='Ej: 4T-501C', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('compresion', 'Compresión'), ('soporte', 'Soporte'), ('combinados', 'Combinados')], default='soporte', max_length=20, verbose_name='Tipo')),
                ('cantidad_total', models.PositiveIntegerField(default=0, verbose_name='Cantidad total')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Modelo de Balancín',
                'verbose_name_plural': 'Modelos de Balancines',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='app_usuario_email_00f306_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='app_usuario_rol_db79e1_idx',
        ),
        migrations.AddField(
            model_name='historialrepuesto',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.repuestobalancin'),
        ),
        migrations.AddField(
            model_name='balancinindividual',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balancines_individuales', to='app.tipobalancin'),
        ),
    ]
