# Generated by Django 4.2.7 on 2026-02-05 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_balancinindividual_estado_historialbalancin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('creacion', 'Creación'), ('actualizacion', 'Actualización')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_restante', models.PositiveIntegerField(verbose_name='Stock restante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.repuestoadicional')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Repuesto Adicional',
                'verbose_name_plural': 'Historial de Repuestos Adicionales',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('CHECKOUT', 'Retiro/Salida'), ('CHECKIN', 'Ingreso/Entrada'), ('STATUS_CHANGE', 'Cambio de Estado'), ('VIEW', 'Consulta'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('BACKUP', 'Respaldo'), ('EXPORT', 'Exportación')], max_length=50, verbose_name='Acción')),
                ('module', models.CharField(choices=[('BALANCIN_INDIVIDUAL', 'Balancín Individual'), ('TIPO_BALANCIN', 'Tipo de Balancín'), ('REPUESTO_BALANCIN', 'Repuesto de Balancín'), ('REPUESTO_ADICIONAL', 'Repuesto Adicional'), ('USER', 'Usuario'), ('SYSTEM', 'Sistema'), ('INVENTORY', 'Inventario General')], max_length=50, verbose_name='Módulo')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Objeto')),
                ('object_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividades',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='app_activit_created_969895_idx'), models.Index(fields=['user'], name='app_activit_user_id_385657_idx'), models.Index(fields=['action'], name='app_activit_action_74eff8_idx'), models.Index(fields=['module'], name='app_activit_module_f8402d_idx'), models.Index(fields=['object_id'], name='app_activit_object__52eb02_idx')],
            },
        ),
    ]
