# Generated by Django 4.2.7 on 2026-02-13 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('rol', models.CharField(choices=[('jefe', 'Jefe'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico')], default='tecnico', max_length=20, verbose_name='rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('ultima_actividad', models.DateTimeField(auto_now=True, verbose_name='última actividad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'inventory_usuario',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='BalancinIndividual',
            fields=[
                ('codigo', models.CharField(help_text='Ej: BAL-16N/4TR-0001', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('sentido', models.CharField(choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente')], default='ASCENDENTE', max_length=20, verbose_name='Sentido')),
                ('rango_horas_cambio_oh', models.PositiveIntegerField(default=30000, help_text='Horas de operación antes de requerir mantenimiento', verbose_name='Rango de horas para cambio de OH')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Balancín Individual',
                'verbose_name_plural': 'Balancines Individuales',
                'db_table': 'inventory_balancinindividual',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Línea',
                'verbose_name_plural': 'Líneas',
                'db_table': 'inventory_linea',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoAdicional',
            fields=[
                ('item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True, verbose_name='Último movimiento')),
                ('fecha_ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Última salida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Repuesto Adicional',
                'verbose_name_plural': 'Repuestos Adicionales',
                'db_table': 'inventory_repuestoadicional',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoBalancin',
            fields=[
                ('item', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('fecha_ultimo_movimiento', models.DateTimeField(auto_now=True, verbose_name='Último movimiento')),
                ('fecha_ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Última salida')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Repuesto para Balancín',
                'verbose_name_plural': 'Repuestos para Balancines',
                'db_table': 'inventory_repuestobalancin',
                'ordering': ['item'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'inventory_seccion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoBalancin',
            fields=[
                ('codigo', models.CharField(help_text='Ej: 16N/4TR-420C', max_length=50, primary_key=True, serialize=False, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('compresion', 'Compresión'), ('soporte', 'Soporte'), ('combinados', 'Combinados')], default='soporte', max_length=20, verbose_name='Tipo')),
                ('cantidad_total', models.PositiveIntegerField(default=0, verbose_name='Cantidad total')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Modelo de Balancín',
                'verbose_name_plural': 'Modelos de Balancines',
                'db_table': 'inventory_tipobalancin',
                'ordering': ['tipo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_torre', models.CharField(max_length=10, verbose_name='Número de torre')),
                ('tipo_balancin_ascendente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo balancín ascendente')),
                ('tipo_balancin_descendente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo balancín descendente')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('linea', models.ForeignKey(db_column='linea_id', on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='balancines.linea')),
                ('seccion', models.ForeignKey(db_column='seccion_id', on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='balancines.seccion')),
            ],
            options={
                'verbose_name': 'Torre',
                'verbose_name_plural': 'Torres',
                'db_table': 'inventory_torre',
                'ordering': ['linea', 'numero_torre'],
                'unique_together': {('linea', 'numero_torre', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de actividad',
                'verbose_name_plural': 'registros de actividad',
                'db_table': 'inventory_registroactividad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_restante', models.PositiveIntegerField(verbose_name='Stock restante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('repuesto', models.ForeignKey(db_column='repuesto_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='balancines.repuestobalancin')),
            ],
            options={
                'verbose_name': 'Historial de Repuesto',
                'verbose_name_plural': 'Historial de Repuestos',
                'db_table': 'inventory_historialrepuesto',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBalancin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado nuevo')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de cambio')),
                ('balancin', models.ForeignKey(db_column='balancin_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='balancines.balancinindividual', verbose_name='Balancín')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Balancín',
                'verbose_name_plural': 'Historial de Balancines',
                'db_table': 'inventory_historialbalancin',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('creacion', 'Creación'), ('actualizacion', 'Actualización')], max_length=20, verbose_name='Tipo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('stock_restante', models.PositiveIntegerField(verbose_name='Stock restante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('repuesto', models.ForeignKey(db_column='repuesto_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='balancines.repuestoadicional')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Repuesto Adicional',
                'verbose_name_plural': 'Historial de Repuestos Adicionales',
                'db_table': 'inventory_historialadicional',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='balancinindividual',
            name='torre',
            field=models.ForeignKey(db_column='torre_id', on_delete=django.db.models.deletion.CASCADE, related_name='balancines', to='balancines.torre', verbose_name='Torre'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('CHECKOUT', 'Retiro/Salida'), ('CHECKIN', 'Ingreso/Entrada'), ('STATUS_CHANGE', 'Cambio de Estado'), ('VIEW', 'Consulta'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('BACKUP', 'Respaldo'), ('EXPORT', 'Exportación')], max_length=50, verbose_name='Acción')),
                ('module', models.CharField(choices=[('BALANCIN_INDIVIDUAL', 'Balancín Individual'), ('TIPO_BALANCIN', 'Tipo de Balancín'), ('REPUESTO_BALANCIN', 'Repuesto de Balancín'), ('REPUESTO_ADICIONAL', 'Repuesto Adicional'), ('TORRE', 'Torre'), ('LINEA', 'Línea'), ('USER', 'Usuario'), ('SYSTEM', 'Sistema'), ('INVENTORY', 'Inventario General')], max_length=50, verbose_name='Módulo')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del Objeto')),
                ('object_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividades',
                'db_table': 'inventory_activitylog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalancinOH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_oh', models.PositiveIntegerField(verbose_name='Número de OH')),
                ('fecha_oh', models.DateField(verbose_name='Fecha de OH')),
                ('horas_operacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas de operación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('balancin', models.ForeignKey(db_column='balancin_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_horas', to='balancines.balancinindividual', verbose_name='Balancín')),
            ],
            options={
                'verbose_name': 'Orden de Horas de Balancín',
                'verbose_name_plural': 'Órdenes de Horas de Balancines',
                'db_table': 'inventory_balancin_oh',
                'ordering': ['-fecha_oh'],
                'unique_together': {('balancin', 'numero_oh')},
            },
        ),
        migrations.AddIndex(
            model_name='balancinindividual',
            index=models.Index(fields=['torre', 'sentido'], name='inventory_b_torre_i_fefd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='inventory_a_created_fcdbcb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='inventory_a_user_id_0b71fb_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='inventory_a_action_c8fb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['module'], name='inventory_a_module_d7a720_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['object_id'], name='inventory_a_object__f2ffb2_idx'),
        ),
    ]
