# Generated by Django 4.2.7 on 2026-02-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea_nombre', models.CharField(max_length=50, verbose_name='Línea')),
                ('torre_numero', models.CharField(max_length=10, verbose_name='Torre')),
                ('sentido', models.CharField(max_length=20, verbose_name='Sentido')),
                ('tipo_balancin', models.CharField(max_length=50, verbose_name='Tipo')),
                ('rango_oh_horas', models.IntegerField(verbose_name='Rango OH (horas)')),
                ('inicio_oc', models.DateField(verbose_name='Inicio OC')),
                ('horas_promedio_dia', models.IntegerField(verbose_name='Horas promedio/día')),
                ('factor_correccion', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Factor')),
                ('numero_oh', models.IntegerField(verbose_name='N° OH')),
                ('fecha_oh', models.DateField(verbose_name='Fecha OH')),
                ('horas_operacion', models.IntegerField(blank=True, null=True, verbose_name='Horas operación')),
                ('backlog', models.IntegerField(blank=True, null=True, verbose_name='Backlog')),
                ('anio', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('dia_semana', models.CharField(blank=True, max_length=20, verbose_name='Día semana')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('usuario_registro', models.CharField(blank=True, max_length=100, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial OH',
                'verbose_name_plural': 'Historiales OH',
                'db_table': 'app_historial_oh',
                'ordering': ['linea_nombre', 'torre_numero', 'sentido', 'numero_oh'],
            },
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='app_activit_created_969895_idx',
            old_name='inventory_a_created_fcdbcb_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='app_activit_user_id_385657_idx',
            old_name='inventory_a_user_id_0b71fb_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='app_activit_action_74eff8_idx',
            old_name='inventory_a_action_c8fb2f_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='app_activit_module_f8402d_idx',
            old_name='inventory_a_module_d7a720_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='app_activit_object__52eb02_idx',
            old_name='inventory_a_object__f2ffb2_idx',
        ),
        migrations.RenameIndex(
            model_name='balancinindividual',
            new_name='app_balanci_torre_i_b5ff30_idx',
            old_name='inventory_b_torre_i_fefd1d_idx',
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='app_activitylog',
        ),
        migrations.AlterModelTable(
            name='balancinindividual',
            table='app_balancinindividual',
        ),
        migrations.AlterModelTable(
            name='balancinoh',
            table='app_balancin_oh',
        ),
        migrations.AlterModelTable(
            name='historialadicional',
            table='app_historialadicional',
        ),
        migrations.AlterModelTable(
            name='historialbalancin',
            table='app_historialbalancin',
        ),
        migrations.AlterModelTable(
            name='historialrepuesto',
            table='app_historialrepuesto',
        ),
        migrations.AlterModelTable(
            name='linea',
            table='app_linea',
        ),
        migrations.AlterModelTable(
            name='registroactividad',
            table='app_registroactividad',
        ),
        migrations.AlterModelTable(
            name='repuestoadicional',
            table='app_repuestoadicional',
        ),
        migrations.AlterModelTable(
            name='repuestobalancin',
            table='app_repuestobalancin',
        ),
        migrations.AlterModelTable(
            name='seccion',
            table='app_seccion',
        ),
        migrations.AlterModelTable(
            name='tipobalancin',
            table='app_tipobalancin',
        ),
        migrations.AlterModelTable(
            name='torre',
            table='app_torre',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='app_usuario',
        ),
        migrations.AddField(
            model_name='historialoh',
            name='balancin',
            field=models.ForeignKey(db_column='balancin_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='historial_oh_completo', to='balancines.balancinindividual'),
        ),
        migrations.AddIndex(
            model_name='historialoh',
            index=models.Index(fields=['linea_nombre', 'torre_numero'], name='app_histori_linea_n_0e87dd_idx'),
        ),
        migrations.AddIndex(
            model_name='historialoh',
            index=models.Index(fields=['fecha_oh'], name='app_histori_fecha_o_91e5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialoh',
            index=models.Index(fields=['anio'], name='app_histori_anio_688b89_idx'),
        ),
        migrations.AddIndex(
            model_name='historialoh',
            index=models.Index(fields=['backlog'], name='app_histori_backlog_6d2c46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historialoh',
            unique_together={('balancin', 'numero_oh')},
        ),
    ]
