# Generated by Django 4.2.7 on 2026-02-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0002_historialoh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBalancinRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_estandar', models.PositiveIntegerField(default=1, verbose_name='Cantidad estándar requerida')),
                ('repuesto', models.ForeignKey(db_column='repuesto_id', on_delete=django.db.models.deletion.CASCADE, related_name='tipos_configurados', to='balancines.repuestobalancin')),
                ('tipo_balancin', models.ForeignKey(db_column='tipo_balancin_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='repuestos_configurados', to='balancines.tipobalancin')),
            ],
            options={
                'db_table': 'app_tipobalancin_repuesto',
                'unique_together': {('tipo_balancin', 'repuesto')},
            },
        ),
    ]
