# Generated by Django 4.2.7 on 2026-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0003_tipobalancinrepuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='color',
            field=models.CharField(default='secondary', max_length=30, verbose_name='Color Bootstrap'),
        ),
        migrations.AlterField(
            model_name='balancinindividual',
            name='rango_horas_cambio_oh',
            field=models.PositiveIntegerField(default=40000, help_text='Horas de operación antes de requerir mantenimiento', verbose_name='Rango de horas para cambio de OH'),
        ),
        migrations.DeleteModel(
            name='TipoBalancinRepuesto',
        ),
    ]
