# Generated by Django 4.2.7 on 2026-02-25 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0004_linea_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioControlOH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_inicial_sentido', models.CharField(choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente')], max_length=20)),
                ('posicion_final_sentido', models.CharField(choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente')], max_length=20)),
                ('fecha', models.DateField()),
                ('horas_funcionamiento', models.IntegerField(blank=True, null=True)),
                ('codigo_formulario', models.CharField(max_length=100, unique=True)),
                ('analisis_particulas', models.BooleanField(default=False)),
                ('analisis_observaciones', models.TextField(blank=True)),
                ('analisis_realizado_por', models.CharField(blank=True, max_length=100)),
                ('analisis_firma', models.CharField(blank=True, max_length=100)),
                ('analisis_codigo_informe', models.CharField(blank=True, max_length=100)),
                ('realizado_firma', models.CharField(blank=True, max_length=100)),
                ('aprobado_firma', models.CharField(blank=True, max_length=100)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('balancin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancines.balancinindividual')),
                ('historial_oh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='balancines.historialoh')),
                ('posicion_final_linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_finales', to='balancines.linea')),
                ('posicion_final_torre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_finales', to='balancines.torre')),
                ('posicion_inicial_linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_iniciales', to='balancines.linea')),
                ('posicion_inicial_torre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_iniciales', to='balancines.torre')),
                ('realizado_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_realizados', to=settings.AUTH_USER_MODEL)),
                ('tipo_balancin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancines.tipobalancin')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_formulario_control_oh',
            },
        ),
        migrations.CreateModel(
            name='FormularioControlDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_nombre', models.CharField(max_length=100)),
                ('nivel_jerarquia', models.IntegerField()),
                ('item_padre', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_disponible_en_balancin', models.IntegerField()),
                ('cantidad_reemplazada', models.IntegerField(default=0)),
                ('fue_reemplazado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='balancines.formulariocontroloh')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancines.repuestobalancin')),
            ],
            options={
                'db_table': 'app_formulario_control_detalle',
            },
        ),
        migrations.CreateModel(
            name='ComposicionBalancin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto_principal', models.CharField(max_length=100, verbose_name='Conjunto')),
                ('conjunto_orden', models.IntegerField(verbose_name='Orden del conjunto')),
                ('item_padre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item padre')),
                ('item_hijo', models.CharField(db_index=True, max_length=50, verbose_name='Item hijo')),
                ('descripcion_hijo', models.TextField(blank=True, verbose_name='Descripción')),
                ('cantidad_por_padre', models.IntegerField(default=1, verbose_name='Cantidad por padre')),
                ('cantidad_total_por_balancin', models.IntegerField(verbose_name='Cantidad total en balancín')),
                ('nivel_jerarquia', models.IntegerField(verbose_name='Nivel jerárquico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('tipo_balancin', models.ForeignKey(db_column='tipo_balancin_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='composicion', to='balancines.tipobalancin')),
            ],
            options={
                'verbose_name': 'Composición de Balancín',
                'verbose_name_plural': 'Composiciones de Balancines',
                'db_table': 'app_composicion_balancin',
                'ordering': ['tipo_balancin', 'conjunto_orden', 'nivel_jerarquia', 'item_padre'],
                'indexes': [models.Index(fields=['tipo_balancin', 'conjunto_orden'], name='app_composi_tipo_ba_465007_idx'), models.Index(fields=['item_hijo'], name='app_composi_item_hi_aa530f_idx')],
            },
        ),
    ]
