# Generated by Django 4.2.7 on 2026-02-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0005_formulariocontroloh_formulariocontroldetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRepuestosPorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.CharField(help_text='Ej: 10870308', max_length=20, verbose_name='ID Excel')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad_por_balancin', models.PositiveIntegerField(default=1, verbose_name='Cantidad por balancín')),
                ('grupo', models.CharField(choices=[('POLEAS', 'Poleas'), ('SEGMENTOS_2P', 'Segmentos 2P'), ('SEGMENTOS_4P', 'Segmentos 4P'), ('CONJUNTOS', 'Conjuntos'), ('OTROS', 'Otros')], default='OTROS', max_length=20, verbose_name='Grupo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurado_en_tipos', to='balancines.repuestobalancin', verbose_name='Repuesto')),
                ('tipo_balancin', models.ForeignKey(db_column='tipo_balancin_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='config_repuestos', to='balancines.tipobalancin', verbose_name='Tipo de balancín')),
            ],
            options={
                'verbose_name': 'Configuración de repuestos por tipo',
                'verbose_name_plural': 'Configuraciones de repuestos por tipo',
                'db_table': 'app_config_repuestos_tipo',
                'ordering': ['tipo_balancin', 'grupo', 'orden'],
                'unique_together': {('tipo_balancin', 'repuesto')},
            },
        ),
        migrations.RemoveField(
            model_name='formulariocontroldetalle',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='formulariocontroldetalle',
            name='repuesto',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='aprobado_usuario',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='balancin',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='historial_oh',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='posicion_final_linea',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='posicion_final_torre',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='posicion_inicial_linea',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='posicion_inicial_torre',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='realizado_usuario',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='tipo_balancin',
        ),
        migrations.RemoveField(
            model_name='formulariocontroloh',
            name='usuario_creacion',
        ),
        migrations.DeleteModel(
            name='ComposicionBalancin',
        ),
        migrations.DeleteModel(
            name='FormularioControlDetalle',
        ),
        migrations.DeleteModel(
            name='FormularioControlOH',
        ),
    ]
