# Generated by Django 4.2.7 on 2026-02-25 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0006_configuracionrepuestosportipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioReacondicionamiento',
            fields=[
                ('codigo_formulario', models.CharField(help_text='Ej: TRM-FCRB-16N-4TR-420C-001', max_length=50, primary_key=True, serialize=False, verbose_name='Código formulario')),
                ('tipo', models.CharField(choices=[('4T-501C', '4T-501C'), ('6T-501C', '6T-501C'), ('8T-501C', '8T-501C'), ('10T-501C', '10T-501C'), ('12T-501C', '12T-501C'), ('8N/4TR-420C', '8N/4TR-420C'), ('10N/4TR-420C', '10N/4TR-420C'), ('12N/4TR-420C', '12N/4TR-420C'), ('14N/4TR-420C', '14N/4TR-420C'), ('16N/4TR-420C', '16N/4TR-420C'), ('4T/4N-420C', '4T/4N-420C')], max_length=20, verbose_name='Tipo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('horas_funcionamiento', models.PositiveIntegerField(verbose_name='Horas de funcionamiento')),
                ('linea_inicial', models.CharField(blank=True, max_length=50, verbose_name='Línea inicial')),
                ('torre_inicial', models.CharField(blank=True, max_length=50, verbose_name='Torre inicial')),
                ('linea_final', models.CharField(blank=True, max_length=50, verbose_name='Línea final')),
                ('torre_final', models.CharField(blank=True, max_length=50, verbose_name='Torre final')),
                ('control_particulas', models.BooleanField(default=False, verbose_name='Control de partículas magnéticas')),
                ('codigo_informe', models.CharField(blank=True, max_length=50, verbose_name='Código de informe')),
                ('torque_verificado', models.BooleanField(default=False, verbose_name='Torque verificado')),
                ('limpieza_verificada', models.BooleanField(default=False, verbose_name='Limpieza de uniones')),
                ('continuidad_verificada', models.BooleanField(default=False, verbose_name='Continuidad verificada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formularios_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('balancin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios_reacondicionamiento', to='balancines.balancinindividual', verbose_name='Balancín')),
                ('historial_oh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to='balancines.historialoh')),
                ('realizado_por_analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formularios_analisis', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por (análisis)')),
                ('realizado_por_recambio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='formularios_recambio', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por (recambio)')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulario de Reacondicionamiento',
                'verbose_name_plural': 'Formularios de Reacondicionamiento',
                'db_table': 'app_formulario_reacondicionamiento',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemFormularioReacondicionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_original', models.CharField(max_length=20, verbose_name='ID Excel')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad_requerida', models.PositiveIntegerField(verbose_name='Cantidad requerida')),
                ('cantidad_usada', models.PositiveIntegerField(default=0, verbose_name='Cantidad usada')),
                ('fue_reemplazado', models.BooleanField(default=False, verbose_name='¿Fue reemplazado?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('stock_antes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock antes')),
                ('stock_despues', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock después')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balancines.configuracionrepuestosportipo', verbose_name='Configuración original')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='balancines.formularioreacondicionamiento')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balancines.repuestobalancin', verbose_name='Repuesto')),
            ],
            options={
                'verbose_name': 'Item de Formulario',
                'verbose_name_plural': 'Items de Formulario',
                'db_table': 'app_item_formulario_reacondicionamiento',
            },
        ),
    ]
