# Generated by Django 4.2.7 on 2026-02-25 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0007_formularioreacondicionamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionrepuestosportipo',
            name='cantidad_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad total'),
        ),
        migrations.AddField(
            model_name='configuracionrepuestosportipo',
            name='conjunto_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='balancines.configuracionrepuestosportipo', verbose_name='Conjunto padre'),
        ),
        migrations.AddField(
            model_name='configuracionrepuestosportipo',
            name='es_conjunto',
            field=models.BooleanField(default=False, verbose_name='Es un conjunto'),
        ),
        migrations.AlterField(
            model_name='configuracionrepuestosportipo',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configurado_en_tipos', to='balancines.repuestobalancin', verbose_name='Repuesto'),
        ),
    ]
