# Generated by Django 4.2.7 on 2026-03-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0008_configuracionrepuestosportipo_cantidad_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioreacondicionamiento',
            name='sentido_final',
            field=models.CharField(blank=True, choices=[('ASCENDENTE', 'Ascendente'), ('DESCENDENTE', 'Descendente')], help_text='ASCENDENTE o DESCENDENTE según la torre de destino', max_length=20, null=True, verbose_name='Sentido final'),
        ),
    ]
