# Generated by Django 4.2.7 on 2026-03-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0009_formularioreacondicionamiento_sentido_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancinindividual',
            name='estado',
            field=models.CharField(choices=[('OPERANDO', 'Operando'), ('MANTENIMIENTO', 'En Mantenimiento'), ('OH_PENDIENTE', 'OH Pendiente')], db_index=True, default='OPERANDO', help_text='Estado actual del balancín', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='balancinindividual',
            name='fecha_cambio_estado',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que cambió el estado', verbose_name='Fecha cambio de estado'),
        ),
        migrations.AddField(
            model_name='balancinindividual',
            name='observaciones_estado',
            field=models.TextField(blank=True, help_text='Motivo del cambio de estado o notas adicionales', null=True, verbose_name='Observaciones del estado'),
        ),
        migrations.CreateModel(
            name='TecnicoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(blank=True, max_length=100, verbose_name='Firma')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='balancines.formularioreacondicionamiento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Técnico por Formulario',
                'verbose_name_plural': 'Técnicos por Formulario',
                'db_table': 'app_tecnico_formulario',
                'ordering': ['fecha_registro'],
            },
        ),
    ]
