# -*- coding: utf-8 -*-
# Generated by manual
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0010_add_estado_balancin'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancinindividual',
            name='estado',
            field=models.CharField(choices=[('OPERANDO', 'Operando'), ('MANTENIMIENTO', 'En Mantenimiento'), ('OH_PENDIENTE', 'OH Pendiente')], db_index=True, default='OPERANDO', help_text='Estado actual del balancín', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='balancinindividual',
            name='fecha_cambio_estado',
            field=models.DateTimeField(auto_now=True, help_text='Última vez que cambió el estado', verbose_name='Fecha cambio de estado'),
        ),
        migrations.AddField(
            model_name='balancinindividual',
            name='observaciones_estado',
            field=models.TextField(blank=True, help_text='Motivo del cambio de estado o notas adicionales', null=True, verbose_name='Observaciones del estado'),
        ),
    ]
