# Generated by Django 4.2.7 on 2026-03-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0011_add_estado_fields_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaOH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('VERDE', 'Normal'), ('AMARILLO', 'Aviso - 1 mes'), ('NARANJA', 'Próximo - 2 semanas'), ('ROJO', 'Urgente - 1 semana'), ('VENCIDO', 'Vencido')], db_index=True, max_length=20, verbose_name='Nivel de alerta')),
                ('backlog_momento', models.IntegerField(help_text='Horas restantes (positivo) o excedidas (negativo)', verbose_name='Backlog al momento de la alerta')),
                ('horas_operacion_momento', models.PositiveIntegerField(help_text='Horas registradas cuando se generó la alerta', verbose_name='Horas de operación al momento')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de generación')),
                ('fecha_estimada_vencimiento', models.DateField(blank=True, help_text='Fecha estimada para backlog = 0', null=True, verbose_name='Fecha estimada de vencimiento')),
                ('leida', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('resuelta', models.BooleanField(db_index=True, default=False, verbose_name='Resuelta')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la alerta', verbose_name='Observaciones')),
                ('balancin', models.ForeignKey(db_column='balancin_codigo', on_delete=django.db.models.deletion.CASCADE, related_name='alertas_oh', to='balancines.balancinindividual', verbose_name='Balancín')),
                ('formulario_resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to='balancines.formularioreacondicionamiento', verbose_name='Formulario que resolvió la alerta')),
                ('usuario_lectura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_leidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que leyó la alerta')),
            ],
            options={
                'verbose_name': 'Alerta de OverHaul',
                'verbose_name_plural': 'Alertas de OverHaul',
                'db_table': 'app_alerta_oh',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['nivel', 'leida', 'resuelta'], name='app_alerta__nivel_f7966c_idx'), models.Index(fields=['balancin', '-fecha_generacion'], name='app_alerta__balanci_660fe9_idx'), models.Index(fields=['fecha_estimada_vencimiento'], name='app_alerta__fecha_e_1462e6_idx')],
            },
        ),
    ]
