# Generated by Django 4.2.7 on 2026-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0012_add_alerta_oh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaoh',
            name='nivel',
            field=models.CharField(choices=[('VERDE', 'Normal'), ('ALERTA', 'Alerta'), ('VENCIDO', 'Vencido')], db_index=True, max_length=20, verbose_name='Nivel de alerta'),
        ),
    ]
