# Generated by Django 4.2.7 on 2026-03-25 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0013_actualizar_niveles_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroRepuestoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('stock_antes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock antes')),
                ('stock_despues', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock después')),
            ],
            options={
                'db_table': 'app_registro_repuesto_adicional',
            },
        ),
        migrations.CreateModel(
            name='RegistroRepuestoBalancin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('stock_antes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock antes')),
                ('stock_despues', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock después')),
            ],
            options={
                'db_table': 'app_registro_repuesto_balancin',
            },
        ),
        migrations.CreateModel(
            name='RegistroTallerDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('turno', models.CharField(choices=[('manana', 'Mañana (6:00-14:00)'), ('tarde', 'Tarde (14:00-22:00)'), ('noche', 'Noche (22:00-6:00)')], default='manana', max_length=20, verbose_name='Turno')),
                ('area', models.CharField(choices=[('mecanica', 'Mecánica'), ('electromecanica', 'Electromecánica'), ('electronica', 'Electrónica'), ('soldadura', 'Soldadura'), ('inspeccion', 'Inspección'), ('general', 'General')], max_length=20, verbose_name='Área')),
                ('descripcion', models.TextField(verbose_name='¿Qué se hizo?')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('consumibles', models.TextField(blank=True, help_text='Ej: Soldadura E7018 (2kg), Aceite hidráulico (5L), Disolvente (1L)', verbose_name='Consumibles utilizados')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, help_text='Horas hombre totales', max_digits=5, verbose_name='Horas trabajadas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('balancin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_taller', to='balancines.balancinindividual', verbose_name='Balancín trabajado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('repuestos_adicionales_usados', models.ManyToManyField(blank=True, through='balancines.RegistroRepuestoAdicional', to='balancines.repuestoadicional', verbose_name='Repuestos adicionales usados')),
                ('repuestos_balancin_usados', models.ManyToManyField(blank=True, through='balancines.RegistroRepuestoBalancin', to='balancines.repuestobalancin', verbose_name='Repuestos de balancín usados')),
                ('tecnicos', models.ManyToManyField(limit_choices_to={'rol__in': ['tecnico', 'supervisor']}, related_name='registros_taller', to=settings.AUTH_USER_MODEL, verbose_name='Técnicos que participaron')),
            ],
            options={
                'verbose_name': 'Registro de Taller',
                'verbose_name_plural': 'Registros del Taller',
                'db_table': 'app_registro_taller_diario',
                'ordering': ['-fecha', '-turno', '-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='registrorepuestobalancin',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancines.registrotallerdiario'),
        ),
        migrations.AddField(
            model_name='registrorepuestobalancin',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balancines.repuestobalancin'),
        ),
        migrations.AddField(
            model_name='registrorepuestoadicional',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancines.registrotallerdiario'),
        ),
        migrations.AddField(
            model_name='registrorepuestoadicional',
            name='repuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='balancines.repuestoadicional'),
        ),
    ]
