# Generated by Django 4.2.7 on 2026-03-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0014_registrorepuestoadicional_registrorepuestobalancin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrotallerdiario',
            options={'ordering': ['-fecha', '-fecha_registro'], 'verbose_name': 'Registro de Taller', 'verbose_name_plural': 'Registros del Taller'},
        ),
        migrations.RemoveField(
            model_name='registrotallerdiario',
            name='balancin',
        ),
        migrations.RemoveField(
            model_name='registrotallerdiario',
            name='horas_trabajadas',
        ),
        migrations.RemoveField(
            model_name='registrotallerdiario',
            name='tecnicos',
        ),
        migrations.AddField(
            model_name='registrotallerdiario',
            name='cantidad_balancines',
            field=models.PositiveIntegerField(default=1, help_text='Número de balancines trabajados', verbose_name='Cantidad de balancines'),
        ),
        migrations.AddField(
            model_name='registrotallerdiario',
            name='tecnico',
            field=models.ForeignKey(limit_choices_to={'rol__in': ['tecnico', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico que realizó el trabajo'),
        ),
        migrations.AddField(
            model_name='registrotallerdiario',
            name='tipo_balancin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_taller', to='balancines.tipobalancin', verbose_name='Tipo de balancín trabajado'),
        ),
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='turno',
            field=models.CharField(blank=True, choices=[('T1', 'T1 (05:30 - 14:00)'), ('T2', 'T2 (14:00 - 22:30)'), ('T3', 'T3 (22:30 - 05:30)'), ('T4', 'T4 (08:00 - 16:30)'), ('T5', 'T5 (21:00 - 04:00)'), ('T6', 'T6 (19:00 - 03:00)')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
