# Generated by Django 4.2.7 on 2026-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0015_alter_registrotallerdiario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='consumibles',
            field=models.TextField(blank=True, help_text='Ej: Soldadura E7018 (2kg), Aceite hidráulico (5L), Grasa (1kg)', verbose_name='Consumibles utilizados'),
        ),
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha del trabajo (se asigna automáticamente)', null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='turno',
            field=models.CharField(blank=True, choices=[('T1', 'T1 '), ('T2', 'T2 '), ('T3', 'T3 '), ('T4', 'T4 '), ('T5', 'T5 '), ('T6', 'T6 ')], max_length=20, null=True, verbose_name='Turno'),
        ),
    ]
