# Generated by Django 4.2.7 on 2026-03-26 15:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balancines', '0016_alter_registrotallerdiario_consumibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='cantidad_balancines',
            field=models.PositiveIntegerField(default=0, help_text='Número de balancines trabajados', verbose_name='Cantidad de balancines'),
        ),
        migrations.AlterField(
            model_name='registrotallerdiario',
            name='turno',
            field=models.CharField(blank=True, choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], max_length=20, null=True, verbose_name='Turno'),
        ),
        migrations.CreateModel(
            name='ControlHorasBalancin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_base', models.PositiveIntegerField(default=0, help_text='Horas registradas en el último punto de referencia', verbose_name='Horas base')),
                ('fecha_base', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se registraron las horas base', verbose_name='Fecha base')),
                ('horas_actuales', models.PositiveIntegerField(default=0, help_text='Horas calculadas en tiempo real', verbose_name='Horas actuales')),
                ('backlog_actual', models.IntegerField(default=0, help_text='Horas restantes para mantenimiento', verbose_name='Backlog actual')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('balancin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_horas', to='balancines.balancinindividual', verbose_name='Balancín')),
                ('ultimo_oh_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_horas', to='balancines.historialoh', verbose_name='Último OH relacionado')),
            ],
            options={
                'verbose_name': 'Control de Horas de Balancín',
                'verbose_name_plural': 'Controles de Horas de Balancines',
                'db_table': 'app_control_horas_balancin',
            },
        ),
    ]
